version: '0.1'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    platform: linux/amd64
    restart: unless-stopped
    mem_limit: 4g
    build:
      context: ./backend_api
      dockerfile: ./Dockerfile

volumes:
  db:
    driver: local